graphql {
  buildIntrospection = true
}
package {
  packageName = "demo.gp.order"
  localPackageNames = ["io.graphoenix.jsonschema", "io.graphoenix.introspection",]
}
r2dbc {
  driver = "mariadb"
  database = "order"
  user = "root"
  password = "root"
}
rabbitmq {
  username = "guest"
  password = "guest"
}
gossip {
  port = 9090
}